# sequence
coursera -edX

What is data science   - Introduction to data science
Open Source tools for Data Science - data science tools
Data Science Methodology - the data science method
Python for Data Science and AI  - python basics for data science/AI for everyone
Databases and SQL for Data Science  - SQL for Data Science
Data Analysis with Python     - Anaizing data with python
Data Visualization with Python - visulization data with python
Machine Learning with Python - Machine Learning with pthon - practical info
Applied Data Science Capstone  - Data science and ML capstone proj




In [5]:
import matplotlib.pyplot as plt

## Data Type

In [4]:
print(int('5'))
print(type('5'))

5
<class 'str'>


In [5]:
#boolean operators
bool(1) # bool (0) False   & bool(True) also give True

True

## String

In [13]:
#replace
A='I am the best'
B=A.replace('I am','You are')
print(B)

# find
print(A.find('am')) # gives the first index

print(A.find('srr'))   # if not available then the output is -1

print(r" \ ")   # giving space is imp and double quote

You are the best
2
-1


In [16]:
#slicing
Numbers="0123456"
Numbers[::2]

'0246'

## Lists and Tuples

In [28]:
#adding tuple
tuple1=('disco',10,5)
tuple1=tuple1+('aa',1)
tuple1[0:1]    # last range need to be 1 higher

('disco',)

In [29]:
# nesting tuples

tuple1=('disco',10,5,('xyz','b'))
tuple1[3][0][0]   # 1st eliment

'x'

In [60]:
l=[1,2,3,4,'a a']
l.extend([5,5])   #concatinate
l.append(['a',6])  # add it as a one eliment
del(l[0])    # deletion
split_=l[3].split(' ')  #spliting the list
l.insert(2,'a')  # inserting to perticular index
c=l.copy()   # create a seperate file

print(l)
print(split_)

[2, 3, 'a', 4, 'a a', 5, 5, ['a', 6]]
['a', 'a']


In [50]:
help(l)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

## Sets

In [65]:
l=['a',2,3,4,'a']
set1={'aa','bb','cc','aa'}
print(set1)  # removes duplicate values
set2=set(l)  # l is a list
print(set2)  # unordered unique values


# Nested list won't work for set - TypeError: unhashable type: 'list'

{'aa', 'bb', 'cc'}
{2, 3, 'a', 4}


In [5]:
set1={'aa','bb','cc','aa',11}
set1.add('ee')  # adds values
set1.remove('aa')   # removes all including duplicate
print('bb' in set1)  # boolean operation
print(set1)

#intersetion
set2={'ee', 'bb', 'cc','dd'}
set3=set1&set2
print(set3)

#union
set4=set2.union(set1)
print(set4)

#difference
set_5=set1.difference(set2)    # values which are available in set 1 but not in set2 
print(set_5)

#check subset
print(set2.issubset(set4))  #boolean result

# Check if superset

print(set(set1).issuperset(set2))

True
{'bb', 11, 'ee', 'cc'}
{'ee', 'cc', 'bb'}
{'dd', 'bb', 11, 'ee', 'cc'}
{11}
True
False


## Dictionary

In [11]:
D={'a':0,'b':1,'c':2}

#values
D.values()

#Keys
D.keys()

#add key
D['e']=5
print(D)

#delete
del(D['a'])
print(D)

{'a': 0, 'b': 1, 'c': 2, 'e': 5}
{'b': 1, 'c': 2, 'e': 5}


## IF ELSE (Conditions and branching)

In [12]:
x='a'
if(x=='a') or (x=='b'):   #or statement
    if (x=='a'):    #nested loop
        print("this is a")
    else:
        print("this is b")
elif X=='c':       #elif
    print("this is c")
else:
    print("this is not a,b or c")

this is a


## Loops & enumerate function

In [17]:
#enumerate function gives index as well as value
cols=['red','green','blue']
for i,col in enumerate(cols):
    print(i)   # gives index
    print(col)# value

0
red
1
green
2
blue


## sorted vs sort

In [20]:
#sorted is a function an sort is a method

A=[2,5,6,8,1,5,6]
print(sorted(A))  # does not change the original new list creates
print(A)

A.sort()     # original sort method
print(A)

[1, 2, 5, 5, 6, 6, 8]
[2, 5, 6, 8, 1, 5, 6]
[1, 2, 5, 5, 6, 6, 8]


## funtions

In [37]:
#help on the function

#The statement return exits a function, optionally passing back a value


def mult(a,b):   #more parameters are given
    '''multiplication'''   # help on the defined funtion in tripple quote and can be checked using help()
    c=a*b
    return c
    print(f'{a} multiplies {b}={c}')  # if return is before this statement will not be executed

help(mult)
mult(5,6)

Help on function mult in module __main__:

mult(a, b)
    multiplication



30

In [28]:
# none results
def no_work():
    pass

print(no_work())

None


In [42]:
#local & global variable

### variables in the fucntions are local variables (only limited to function) unless mentioned global in the function

def any_date():
    date=1993    # local variable (witin the function its defined)
    print(date)

date=2020 # global variable (set outside of the function)

any_date()  #local variable
 
print(date)   # takes global variable


######################################################
#local & global variable

def any_date():
    global date # this set a global date variable
    date=1993   
    print(date)

date=2020 # global variable (set outside of the function - can be changed by setting global form function)

any_date()  
 
print(date)   # now taking set global variable inside the function

1993
2020
1993
1993


In [49]:
def f(c):
    return sum(c)
f([1,2,3])

6

In [52]:
def type_of_album(artist, album, year_released):
    
    print(artist, album, year_released)
    if year_released > 1980:
        return "Modern"
    else:
        return "Oldie"
print(type_of_album('a','b',1922))

a b 1922
Oldie


In [53]:
# Example for setting param with default value

def isGoodRating(rating=4): 
    if(rating < 7):
        print("this album sucks it's rating is",rating)
        
    else:
        print("this album is good its rating is",rating)

In [56]:
def con(a, b):
    return(a + b)
con(5,1)

6

## Class and objects

In [18]:
class Circle(object):
    def __init__(self,radius,color):
        self.radius=radius;
        self.color=color;
    def circle_info(self):
        print(self.radius)
        print(self.color)
    def add_radius(self,r):
        self.radius=self.radius+r
        return self.radius

In [27]:
A=Circle(2,'red')
A.add_radius(5)
A.circle_info()

7
red


In [13]:
# Create a class Circle

class Circle(object):
    #The next step is a special method called a constructor __init__, which is used to initialize the object. 

    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color 
    
    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return(self.radius)
    
    # Method
    def drawCircle(self):
        plt.gca().add_patch(plt.Circle((0, 0), radius=self.radius, fc=self.color))
        plt.axis('scaled')
        plt.show()  

dir(Circle)   #check directory of the class

In [14]:
RedCircle = Circle(10, 'red')

In [22]:
RedCircle.radius

10

# Read Data

In [48]:
text_file=open('C:\\Users\\PASHYA\\Desktop\\Pandas_Demo\\data.txt','r')  #\ used to escape

# r for reading, w for writing, a for append

In [49]:
text_file.name
text_file.mode
#text_file.close()  #always needs to close the file for OPEN function

'r'

In [50]:
file_data=text_file.read()

In [51]:
print(file_data)  # str type data

1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5
3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12
1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88



In [52]:
text_file.closed   # gives boolean output

False

In [53]:
#with function no need to close the file

with open('ref_data/data_1.txt','r') as text_file_1:
    file_stuff=text_file_1.read()   # all the code need to type in indent
    file_stuff=text_file_1.readline(4)   # for loop can be used to read lines
    print(file_stuff)

print(text_file_1.closed)  



True


In [74]:
with open('ref_data/data_2.txt','w') as file_1:
    file_1.write('This is line A\n')
    file_1.write('This is line B\n')    # \n is for the new line
    file_1.write('This is line C\n')

print()
with open('ref_data/data_2.txt','a') as file_1:    # a will append the file
    file_1.write('This is line A\n')
    file_1.write('This is line B\n')    # \n is for the new line
    file_1.write('This is line C\n')

In [76]:
file_1=open('ref_data/data_2.txt','r')
file_stuff=file_1.read()   # readline to read the line
print(file_stuff)

file_stuff=file_1.readline()   # readline to read the line
print(file_stuff)

file_stuff=file_1.readline()   # successively used will give the 2nd line
print(file_stuff)

file_stuff=file_1.readline(5)   # number of 1st letters to read
print(file_stuff)

This is line A
This is line B
This is line C
This is line A
This is line B
This is line C






In [80]:
lines=['This is line A\n','This is line B\n','This is line C\n']   #using list

with open('ref_data/data_2.txt','w') as file_1:
    for line in lines:
        file_1.write(line)

file_1=open('ref_data/data_2.txt','r')
file_stuff=file_1.read()   # readline to read the line
print(file_stuff)


This is line A
This is line B
This is line C



In [82]:
# creating a copy

with open('ref_data/data_2.txt','r') as readfile:
    with open('ref_data/data_3.txt','w') as writefile:
        for line in readfile:
            writefile.write(line)
file_1=open('ref_data/data_3.txt','r')
file_stuff=file_1.read()   # readline to read the line
print(file_stuff)

This is line A
This is line B
This is line C



## reading data with pandas

In [83]:
import pandas as pd

In [84]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_np_version_under1p

In [85]:
# read csv

df=pd.read_csv('ref_data/covid_19_data.csv')  #simlar read_excel/json

In [87]:
# head
df.head()  #by default it will give 5 results; number can be mentioned for number of req columns

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [89]:
# dataframe from Dictionary (keys will be column name, vlaues will be row line items)

dict_1={'a':[1,2,3,4],
       'b':['a',2,3,4]}
df=pd.DataFrame(dict_1)
print(df)

In [93]:
df=pd.read_csv('ref_data/covid_19_data.csv')

# unique values
df['Country/Region'].unique()

array(['Mainland China', 'Hong Kong', 'Macau', 'Taiwan', 'US', 'Japan',
       'Thailand', 'South Korea', 'Singapore', 'Philippines', 'Malaysia',
       'Vietnam', 'Australia', 'Mexico', 'Brazil', 'Colombia', 'France',
       'Nepal', 'Canada', 'Cambodia', 'Sri Lanka', 'Ivory Coast',
       'Germany', 'Finland', 'United Arab Emirates', 'India', 'Italy',
       'UK', 'Russia', 'Sweden', 'Spain', 'Belgium', 'Others', 'Egypt',
       'Iran', 'Israel', 'Lebanon', 'Iraq', 'Oman', 'Afghanistan',
       'Bahrain', 'Kuwait', 'Austria', 'Algeria', 'Croatia',
       'Switzerland', 'Pakistan', 'Georgia', 'Greece', 'North Macedonia',
       'Norway', 'Romania', 'Denmark', 'Estonia', 'Netherlands',
       'San Marino', ' Azerbaijan', 'Belarus', 'Iceland', 'Lithuania',
       'New Zealand', 'Nigeria', 'North Ireland', 'Ireland', 'Luxembourg',
       'Monaco', 'Qatar', 'Ecuador', 'Azerbaijan', 'Czech Republic',
       'Armenia', 'Dominican Republic', 'Indonesia', 'Portugal',
       'Andorra', 'Latvia

In [95]:
#use bool to create dataframe

df1=df[df['Confirmed']>=50000]   # boolean reasults needs to placed in df

# df.to_csv('xxxx.csv') to save the file

## numpy

In [1]:
import numpy as np

In [100]:
# 1D array
a=np.array([0,1,2,3,4])  
a[0]  #similar to list

0

In [99]:
type(a)

numpy.ndarray

In [101]:
a.dtype   #int32

dtype('int32')

In [104]:
# size
a.size

5

In [105]:
#shape
a.shape

(5,)

In [8]:
#2D array
a=[[1,2,3],[4,5,6],[7,8,9]]
A=np.array(a)

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#axis or dimention of the array
A.ndim


2

In [14]:
#shape
A.shape

(3, 3)

In [16]:
# call values
A[0][0]

#or
A[0,0]

1

In [17]:
#slicing
A[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [21]:
#multiplication 

A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])
Z=np.dot(A,B)   #C=A*B will not work as shape of array is diff
Z


array([[0, 2],
       [0, 2]])

In [22]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [23]:
#transpose
Z.T

array([[0, 0],
       [2, 2]])